var payload = JSON.stringify({
	model: "gpt-3.5-turbo",
	messages: [
		{
			role: "system",
			content:
				"You are an extension that creates useful information to be shown below a search at google.com",
		},
		{ role: "user", content: document.getElementsByTagName("input")[0].value },
	],
});
fetch("https://api.openai.com/v1/chat/completions", {
	method: "POST",
	headers: {
		"Content-Type": "application/json",
		Authorization: "Bearer ",
	},
	body: payload,
})
	.then(res => res.json())
	.then(response => response.choices[0].message.content)
	.then(message => {
		message.replaceAll(/^(?:[2-9]|\d\d\d*)$/g, "\n$1");
		var outerdiv = `
<div id="assistant" style="white-space: pre-wrap;background-color: #444654; width:50%; border-radius:10px; margin-bottom: 2.5%; padding:10px;"> 
	<div id="title" style="background-color:#3f3f46; height:40%; width: 40%; border-radius:10px; vertical-align:middle; display:flex;">
		<img src="https://chat.openai.com/favicon-32x32.png" style="margin:3px;height:80%; border-radius:10px;position:relative;"></img>
		<p style="vertical-align:middle; margin-left:3%;">Output generated by ChatGPT</p>
		
	</div>
	${message}
</div>`;

		document.getElementById("extabar").innerHTML += outerdiv;
	});
